# Don't print a new line at the start of the prompt
format = """
[Î£ ](bold green)$directory(bold blue)$git_branch$git_status[â¯](bold yellow)[â¯](bold purple)[â¯](bold blue) """
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the "â¯" symbol in the prompt with "âœ"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[âœ](bold green)"  # The "success_symbol" is set to "âœ" with color "bold green"

# Use custom format
# format = """
# [â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€>](bold green)
# [â”‚](bold green)$directory$rust$package
# [â””â”€>](bold green) """

# Disable the package module, hiding it from the prompt completely

[character]
error_symbol = "[âœ—](bold red) "
success_symbol = "[Î£](bold green)"
vicmd_symbol = "[Î£](bold red)"
#format = "$symbol [|](bold bright-black) "
#success_symbol = "[ïŸ ](bold green)"



[package]
format = "[$symbol$version]($style) "
disabled = true
scan_timeout = 60
add_newline = false
symbol = "ï£– "

[directory]
style = "bold blue"

[cmd_duration]
format = "[$duration]($style) "

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = "ï€"
not_executable_symbol = "ï‘®"
sigint_symbol = "ï­¦"
map_symbol = true

[git_branch]
format = "[$symbol$branch]($style) "

[shell]
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = "î˜† "

[lua]
format = "[$symbol($version )]($style)"
symbol = "î˜  "

[nodejs]
format = "[$symbol($version )]($style)"
#symbol = ""

[php]
format = "[$symbol($version )]($style)"
symbol = "î˜ˆ "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = "î‰– "

[rust]
format = "[$symbol($version )]($style)"
symbol = "ğŸ¦€ "

[golang]
format = "[$symbol($version )]($style)"
symbol = "î˜¦ "

[c]
format = "[$symbol($version )]($style)"
symbol = "î˜ "

[perl]
format = "[$symbol($version )]($style)"
symbol = "î© "

[dart]
format = "[$symbol($version )]($style)"
symbol = "î˜ "

[haskell]
format = "[$symbol($version )]($style)"
symbol = "î· "


[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 10
style = "bold red"





#Alternatively
#add_newline = true

## Use custom format
#format="[\uE0B6î‚¶ $directory\uE0B4 î‚´](bg: cyan) $git_branch[ï”](bg: green) "

## Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

## Remove nodejs
#[nodejs]
#disabled = true

#[directory]
#format = "[â¯ $path](bg:cyan fg:black bold)"

#[git_branch]
#symbol = "\ue725 "
#format = "[\uE0B6](bg: green)[on $symbol$branch](bg:green fg:black bold)[\uE0B4](bg: green) "
